languageCode = "en-gb"
title = "Robin Thrift"
baseURL = "https://robinthrift.com"
theme = "hemingway2"
copyright = "&copy; <a href=\"https://github.com/RobinThrift\">Robin Thrift</a> 2019"
pygmentsCodeFences = true
pygmentsUseClasses=true

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "fahrenheit"
languages = [
    "swift",
    "rust",
    "go"
]

[[params.social]]
url = "https://github.com/RobinThrift"
name = "github"

[[params.social]]
url = "https://twitter.com/RobinThrift"
name = "twitter"

[[params.social]]
url = "/index.xml"
name = "rss"
