languageCode = "en-gb"
title = "Robin Thrift"
baseURL = "https://robinthrift.com"
theme = "hemingway2"
copyright = "&copy; <a href=\"https://github.com/RobinThrift\">Robin Thrift</a> 2020"

[taxonomies]
tag = "tags"
category = "categories"

[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = false
tabWidth = 4

[params]

[[params.social]]
url = "https://github.com/RobinThrift"
name = "github"

[[params.social]]
url = "https://twitter.com/RobinThrift"
name = "twitter"

[[params.social]]
url = "/index.xml"
name = "rss"
