languageCode = "en-gb"
title = "Robin Thrift"
baseURL = "https://robinthrift.com"
theme = "theme"
copyright = "&copy; <a href=\"https://github.com/RobinThrift\">Robin Thrift</a> 2023"
enableRobotsTXT = true

[taxonomies]
tag = "tags"
category = "categories"

[markup.highlight]
guessSyntax = false
codeFences = true
style = "catppuccin-frappe"
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
tabWidth = 4

[blackfriday]
hrefTargetBlank = true

[params.rss]
includeContent = true
authorName = "Robin Thrift"

[[params.social]]
name = "github"
url = "https://github.com/RobinThrift"

[[params.social]]
name = "mastodon"
url = "https://hachyderm.io/@RobinThrift"

[[params.social]]
name = "rss"
url = "/index.xml"
