languageCode = "en-gb"
title = "Robin Thrift"
baseURL = "https://robinthrift.com/"
theme = "hemingway2"
copyright = "&copy; <a href=\"https://github.com/RobinThrift\">Robin Thrift</a> 2017"

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "gruvbox-dark"
languages = [
    "swift",
    "rust",
    "go"
]

[[params.social]]
url = "https://github.com/RobinThrift"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/RobinThrift"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
