_default:
    @just --list

install:
    npm i

build: css-build

css-watch:
    ./node_modules/.bin/tailwindcss --watch -i ./styles/style.css -o ./static/css/style.css

css-build:
    ./node_modules/.bin/tailwindcss -m -i ./styles/style.css -o ./static/css/style.css

fonts: _leaguemono _fixel

_leaguemono:
   curl -L https://github.com/theleagueof/league-mono/releases/download/2.300/LeagueMono-2.300.tar.xz -o LeagueMono-2.300.tar.xz
   tar -xzf LeagueMono-2.300.tar.xz
   cp LeagueMono-2.300/static/{OTF,TTF,WOFF,WOFF2}/{LeagueMono-NarrowLight,LeagueMono-NarrowRegular}.* static/fonts/leaguemono/
   curl -L https://raw.githubusercontent.com/theleagueof/league-mono/master/OFL.md > static/fonts/leaguemono/LICENSE
   rm -rf LeagueMono-2.300 LeagueMono-2.300.tar.xz

_fixel:
    curl -L https://fonts.macpaw.com/fonts/FixelAll.zip -o FixelAll.zip
    unzip FixelAll.zip -d FixelAll
    curl -L "https://scripts.sil.org/cms/scripts/render_download.php?format=file&media_id=OFL_plaintext&filename=OFL.txt" -o static/fonts/fixeltext/LICENSE
    cp FixelAll/FixelText/FixelText-{Bold,Regular,Light}.* static/fonts/fixeltext/
    rm -rf FixelAll.zip -d FixelAll

