name: publish

on:
  push:
    branches: master

jobs:
  build:
    env:
      GIT_NAME: "GitHub actions"
      GIT_EMAIL: "robinthrift@users.noreply.github.com"
      SOURCE_DIR: "public"
      DEPLOY_BRANCH: "master"
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_NAME: ${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: curl -L https://github.com/gohugoio/hugo/releases/download/v0.111.3/hugo_0.111.3_linux-amd64.tar.gz -o hugo.tar.gz && tar -xzf hugo.tar.gz
    - name: Build
      run: ./hugo
    - name: Deploy
      run: ./scripts/deploy.sh
